# Generated by Django 4.2.8 on 2025-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "объект «Мероприятие»",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "verbose_name": 'объект "Пользователь Telegram"',
                "verbose_name_plural": "Пользователи Telegram",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="company_info",
            field=models.TextField(verbose_name="Информация о компании организаторе"),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_time",
            field=models.DateTimeField(verbose_name="Дата проведения"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="dress_code",
            field=models.CharField(
                max_length=200, verbose_name="Информация о компании организаторе"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Место проведения"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="subscribed",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="user_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="id"),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Юзернейм"
            ),
        ),
    ]
