# Generated by Django 4.2.8 on 2025-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_event_options_alter_telegramuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="Описание мероприятия"),
        ),
        migrations.AlterField(
            model_name="event",
            name="dress_code",
            field=models.CharField(max_length=200, verbose_name="Дресс-код"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(max_length=200, verbose_name="Место проведения"),
        ),
    ]
