# Generated by Django 4.2.8 on 2025-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_alter_event_description_alter_event_dress_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.TextField(verbose_name="Место проведения"),
        ),
    ]
