version: '3'

volumes:
  pg_data_production:
  static_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: unless-stopped

  eventplanner:
    image: vlad2505/eventplanner 
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/eventplanner_static
    restart: unless-stopped

  gateway:
    image: vlad2505/gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - eventplanner
    restart: unless-stopped

  eventbot:
    image: vlad2505/eventbot
    env_file: .env 
    depends_on:
      - eventplanner
    restart: unless-stopped
