# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data_production:
  static_volume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  eventplanner:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: vlad2505/eventplanner 
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    volumes:
      - static_volume:/eventplanner_static

# Добавляем новый контейнер: gateway.
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    image: vlad2505/gateway   
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80

  eventbot:
    image: vlad2505/eventbot
    env_file: .env  # Используем тот же .env файл, если там есть нужные переменные
    depends_on:
      - eventplanner
